# 아이스크림 가게의 상반기 주문 정보를 담은 FIRST_HALF
# 아이스크림 성분에 대한 정보를 담은 ICECREAM_INFO

SELECT A.FLAVOR
FROM FIRST_HALF as A
JOIN ICECREAM_INFO AS B ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER > 3000 AND B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC;